apiVersion: v1
kind: Service
metadata:
    name: "anwesystutorialproject"
    labels:
        app: "anwesystutorialproject"
spec:
    type: LoadBalancer
    ports:
    - port: 4711
      targetPort: 4711
      protocol: TCP
      name: http
    selector:
        app: "anwesystutorialproject"